POST http://localhost:5000/notes HTTP/1.1
Content-Type: application/json

{
    "note_title": "More quacks",
    "note_body": "QUACK! QUACK! QUACK!"
}

###

POST http://localhost:5000/notes HTTP/1.1
Content-Type: application/json

{
    "note_title": "Battlestar Galactica",
    "note_body": "Fighting evil robots who have boobs and pussies!"
}

###

POST http://localhost:5000/notes HTTP/1.1
Content-Type: application/json

{
    "note_title": "Quack!",
    "note_body": "The ducks are marching!"
}

###

GET http://localhost:5000/notes HTTP/1.1
Content-Type: application/json

###

DELETE http://localhost:5000/notes/1573574056991 HTTP/1.1
Content-Type: application/json 

###

PUT http://localhost:5000/notes/1577289518170 HTTP/1.1
Content-Type: application/json 

{
    "note_title": "Starship Damascus",
    "note_body": "Flying to the farthest stars"
}

### 

GET http://localhost:5000/notes/1580079285843 HTTP/1.1
Content-Type: application/json
